# Generated by Django 4.2.4 on 2023-11-15 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0006_alter_requisition_requisition_status'),
        ('Quotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=100, null=True)),
                ('Price', models.FloatField(default=0)),
                ('Net', models.FloatField(default=0)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition_item')),
                ('Quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Quotation.quotation')),
            ],
        ),
    ]
