# Generated by Django 4.2.4 on 2023-11-15 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quotation', '0002_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='Approved_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotation',
            name='Sub_Total',
            field=models.FloatField(default=0),
        ),
    ]
