# Generated by Django 4.2.4 on 2023-11-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0003_quotation_approved_by_quotation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='Net',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='Price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
