# Generated by Django 4.2.4 on 2023-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0005_quotation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='Reference',
            field=models.CharField(default='QUO-001', max_length=25),
            preserve_default=False,
        ),
    ]
