# Generated by Django 4.2.4 on 2023-11-15 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0006_quotation_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
