# Generated by Django 4.2.4 on 2023-11-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0007_quotation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='LPO_Date',
            field=models.DateField(null=True),
        ),
    ]
