# Generated by Django 4.2.4 on 2023-11-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0010_lpo_po_category_lpo_q_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpo',
            name='PO_NO',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
