# Generated by Django 4.2.4 on 2023-11-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Job_Role',
            field=models.CharField(choices=[('DM', 'Department Manager'), ('PE', 'Project Engineer'), ('PM', 'Purchase Manager'), ('SE', 'Site Engineer'), ('AC', 'Accountant')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Staff_ID',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
