# Generated by Django 4.2.4 on 2023-11-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Auth', '0002_user_job_role_alter_user_mobile_alter_user_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Job_Role',
            field=models.CharField(choices=[('Department Manager', 'Department Manager'), ('Project Engineer', 'Project Engineer'), ('Purchase Manager', 'Purchase Manager'), ('Site Engineer', 'Site Engineer'), ('Accountant', 'Accountant')], max_length=25, null=True),
        ),
    ]
