# Generated by Django 4.2.4 on 2023-11-13 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0003_project_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(default=1)),
                ('Requisition_Status', models.IntegerField(default=1)),
                ('Reference', models.CharField(max_length=50)),
                ('Added_Date', models.DateField(auto_now_add=True)),
                ('Added_IP', models.GenericIPAddressField(null=True)),
                ('Edited_Date', models.DateField(null=True)),
                ('Edited_IP', models.GenericIPAddressField(null=True)),
                ('Added_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_created', to=settings.AUTH_USER_MODEL)),
                ('Edited_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_edited', to=settings.AUTH_USER_MODEL)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Projects.project')),
            ],
        ),
    ]
