# Generated by Django 4.2.4 on 2023-11-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_product_category'),
        ('Requisition', '0002_requisition_approved_by_requisition_checked_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Note', models.CharField(max_length=255, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Core.product')),
                ('Requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
            ],
        ),
    ]
