# Generated by Django 4.2.4 on 2023-11-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0005_remove_requisition_item_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='Requisition_Status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
