# Generated by Django 4.2.4 on 2023-12-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0007_service_service_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='Requisition_Type',
            field=models.IntegerField(default=1),
        ),
    ]
