# Generated by Django 4.2.4 on 2023-12-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0008_requisition_requisition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Title',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
