# Generated by Django 4.2.4 on 2023-12-07 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Requisition', '0009_alter_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='Reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='Rejected_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
