# Generated by Django 4.2.4 on 2023-11-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_Name',
            field=models.CharField(default='project', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_Description',
            field=models.TextField(null=True),
        ),
    ]
