# Generated by Django 4.2.4 on 2023-11-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_project_project_name_project_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Reference',
            field=models.CharField(default='PROJECT-000', max_length=50),
            preserve_default=False,
        ),
    ]
