# Generated by Django 4.2.4 on 2023-12-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_project_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Category', models.IntegerField(default=0)),
                ('Title', models.CharField(max_length=55)),
                ('Amount', models.FloatField(default=0)),
            ],
        ),
    ]
