# Generated by Django 4.2.4 on 2023-12-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_expense_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Expected_Ending_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Job_No',
            field=models.CharField(default='JOB-000', max_length=50),
            preserve_default=False,
        ),
    ]
