# Generated by Django 4.2.4 on 2023-11-08 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0002_category_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Added_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='Added_Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='Added_IP',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Edited_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='Edited_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Edited_IP',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
