# Generated by Django 4.2.4 on 2023-11-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_category_added_by_category_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Reference',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
