# Generated by Django 4.2.4 on 2023-11-13 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0004_alter_category_name_alter_category_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(default=1)),
                ('Added_Date', models.DateField(auto_now_add=True)),
                ('Added_IP', models.GenericIPAddressField(null=True)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Reference', models.CharField(max_length=25, unique=True)),
                ('Unit', models.CharField(max_length=100)),
                ('Note', models.CharField(max_length=250, null=True)),
                ('Added_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
