# Generated by Django 4.2.4 on 2024-01-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Reference', models.CharField(max_length=25, unique=True)),
                ('Note', models.CharField(max_length=250, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_In_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Reference', models.CharField(max_length=25, unique=True)),
                ('Note', models.CharField(max_length=250, null=True)),
                ('Sub_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sub_category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Sub_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.sub_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='Sub_In_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.sub_in_category'),
        ),
    ]
