# Generated by Django 4.2.4 on 2024-03-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_product_category_alter_sub_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_in_category',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
