# Generated by Django 4.2.4 on 2024-01-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_project_expected_ending_date_project_job_no'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='Project',
        ),
        migrations.CreateModel(
            name='Inventory_Out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Quantity', models.CharField(max_length=20, null=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.inventoryitem')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Projects.project')),
            ],
        ),
    ]
