# Generated by Django 4.2.4 on 2024-01-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_remove_inventory_project_inventory_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
    ]
