# Generated by Django 4.2.4 on 2024-01-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_inventory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
