# Generated by Django 4.2.4 on 2024-01-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_inventoryitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='Item',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='Name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
