# Generated by Django 4.2.4 on 2024-01-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_remove_inventoryitem_item_inventoryitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='Reference',
            field=models.CharField(default='ITEM-001', max_length=50),
            preserve_default=False,
        ),
    ]
