# Generated by Django 4.2.4 on 2024-01-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_inventoryitem_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Quantity', models.IntegerField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventoryitem')),
            ],
        ),
    ]
